ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/store/urls.py
from django.urls import path
from . import views
from .views import CreateOrderView, CaptureOrderView


urlpatterns = [
	#Leave as empty string for base url
	path('', views.store, name="store"),
    path('signin', views.signin, name="signin"),
    path('signout', views.signout, name="signout"),
	path('cart/', views.cart, name="cart"),
	path('checkout/', views.checkout, name="checkout"),
	path('update_item/', views.updateItem, name="update_item"),
    path('process_order/', views.processOrder, name="process_order"),
    path('register/', views.register, name="register"),
    path('productview/<str:product_name>', views.productView, name="productview"),
    path('search/', views.search, name="search"),
    path('transaction_sumary/', views.transaction_sumary, name='transaction_sumary'),
    path('api/orders', CreateOrderView.as_view(), name='create_order'),
    path('api/orders/<str:order_id>/capture', CaptureOrderView.as_view(), name='capture_order'),
]

ecommerce/store/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.user) if self.user is not None else "DefaultString"

class Product(models.Model):
    #Category choices for product
    category = [
        ("M", "Men"),
        ("W", "Woman"),
        ("K", "Kids"),
    ]
    name = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits = 7, decimal_places= 2)
    digital = models.BooleanField(default=False, null=True, blank=False)
    image = models.ImageField(null=True, blank=True)
    category = models.CharField(max_length = 1, null=True, choices=category)

    def __str__(self):
        return self.name
    
    @property
    def imageURL(self):
        try: 
            url = self.image.url
        except:
            url = ''
        return url
    
class DiscountProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    discount_price = models.DecimalField(max_digits = 7, decimal_places= 2, default = 0) #I ADDED THIS AFTER
    original_price = models.DecimalField(max_digits = 7, decimal_places= 2, default = 0)  # Add a field for the original price

    def __str__(self):
        return f"Discount for {self.product.name}"
    
class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)

    #Properties for order calculations
    @property
    def qnt_total(self):
        total = 0
        orderitems = self.orderitem_set.all()
        for item in orderitems:
            total += item.quantity
        return total
    
    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping
    
    @property
    def cartTotal(self):

        discountProduct = DiscountProduct.objects.all()
        total = 0
        orderitems = self.orderitem_set.all()

        for item in orderitems:
            try:
                discountProduct = DiscountProduct.objects.get(product=item.product)
                total += item.quantity * discountProduct.discount_price
            except DiscountProduct.DoesNotExist:
                total += item.quantity * item.product.price
        
        return total

    def __str__(self):
        return str(self.id)
    
class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    #Property for calculating total
    @property
    def get_total(self):
        try:
            discountProduct = DiscountProduct.objects.get(product=self.product)
        except DiscountProduct.DoesNotExist:
            discountProduct = None

        if discountProduct:
            total = self.quantity * discountProduct.discount_price
        else:
            total = self.quantity * self.product.price
        return total

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

ecommerce/store/views.py
from .imports import *

#Store view used as homepage
def store(request):
    #Retrieve data using getData function
    context = getData(request)

    #Check if user is logged in
    if request.user.is_authenticated:
            #If so get theuser's first name
            user = request.user
            fname = user.first_name
            #Render the store with data and user's first name
            return render(request, 'store/store.html', {'fname' : fname, **context})
    else:
        #Render the store with only the data
        return render(request, 'store/store.html', context)

#Function to handle user sign-in
def signin(request):
    #Check if the method is post (sent by the login form)
    if request.method == "POST":
        #Retrieve credentials used for login
        username = request.POST['username']
        password = request.POST['password']

        #Use Django's authenticate function
        user = authenticate(username=username, password=password)
        #If authentication was successful, use the login function and redirect store
        if user is not None:
            login(request, user)
            return redirect('store')
        else:
            #User login fails, redirect to store with error message
            messages.error(request, "Bad credentials!", 'user_message')
            return redirect('store')

#Handle the user's logout
def signout (request):
    #Use Django's logout function
    logout(request)
    return redirect('store')

#Handle user's registration
def register(request):
    #Retrieve data using getData function
    context = getData(request)
    cartItems = context['cartItems']
    
    #Handle request via GET
    if request.method == "GET":
        #Redirect to store if user is logged in
        if request.user.is_authenticated:
            customer = request.user.customer
            return redirect('store')
        else:
            #Show registration page 
            return render(request, 'store/register.html', {'cartItems' : cartItems})
    
    #Handle registration process (Form is sent via POST)
    if request.method == "POST":
        #Extract user information from the form
        username = request.POST['username']
        name = request.POST['name']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        #Check for existing username and email
        if User.objects.filter(username=username):
            messages.error(request, "Username already exists", 'user_message')
            return redirect('store')

        if User.objects.filter(email=email):
            messages.error(request, "Email already exists", 'user_message')
            return redirect('store')
        
        #Validate username length, password match, and alphanumeric username
        if len(username)>12:
            messages.error(request, "Username be smaller than 12 characters", 'user_message')
            return redirect('store')
        
        if password != password2:
            messages.error(request, "Passwords didn't match!", 'user_message')
            return redirect('store')
        
        if not username.isalnum():  
            messages.error(request, "Username must be alphanumeric", 'user_message')
            return redirect('store')

        #Create user using Django's create_user function
        myuser = User.objects.create_user(username, email, password)
        #Extract first and last name from the user's full name
        name_words = name.split()
        if len(name_words) > 0:
            myuser.first_name = name_words[0]  
            myuser.last_name = name_words[-1] 
        
        myuser.save()

        #Create a customer associated with the user
        customer, created = Customer.objects.get_or_create(user=myuser)
        customer.name = name
        customer.email = email
        customer.save()

        messages.success(request, "Your account has been successfully created!", 'user_message')

        #Welcome email
        subject = "Welcome to DAVIDUARTE'S Django project!"
        message = "Hello " + myuser.first_name + "!! \n" + "Welcome to our store! \n Thank you for visiting our store! \n We will send you the latest news and promotions we have on our website!"
        #Specify the sender and receiver emails
        from_email = settings.EMAIL_HOST_USER
        to_list = [myuser.email]
        #Use the send_mail function to send the email
        send_mail(subject, message, from_email, to_list, fail_silently=True)

        return redirect('store')

def search(request):
    #Retrieve data using getData function
    context = getData(request)

    #Retrieve the search word from the query parameter
    search_str = request.GET.get("search_str", "")
    #Filter products based on the search category
    search_products = Product.objects.filter(category__iexact=search_str)
    #Replace existing 'products' in context with search results
    context['products'] = search_products
 
    if context['products']:
        #In this case the search was for a category that corresponds to the product
        context['products'] = Product.objects.filter(category__iexact=search_str)
        return render(request, 'store/search.html', context)
    #Check if there are products with names containing the search string
    elif (Product.objects.filter(name__icontains=search_str)):
        context['products'] = Product.objects.filter(name__icontains=search_str)
        return render(request, 'store/search.html', context)
    #Handle case where no products are found
    else:
        messages.error(request, "No products found.")
        return render(request, 'store/search.html', context)

#Product detailed view
def productView(request, product_name):
    #Retrieve data using getData function
    context = getData(request)

    #Get the product using the productName that is sent by html via url
    product = get_object_or_404(Product, name__iexact=product_name)

    #Render the template with the product selected in the store
    return render(request, 'store/productview.html', {'product' : product, **context})

#Cart page
def cart(request):
    #Retrieve data using getData function
    context = getData(request)

    return render(request, 'store/cart.html', context)

def checkout(request):
    #Retrieve data using getData function
    context = getData(request)
    
    return render(request, 'store/checkout.html', context)

#Handle adding or removing items in the order
def updateItem(request):
    #Retrieve the data of the html
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    #Get the value to add or remove (if it is from arrows interface, it is set to 1, else it is specified by the user)
    quantity_value = data.get('quantityValue', 1)

    print('Action:', action)
    print('Product:', productId)

    #Get the current customer
    customer = request.user.customer
    #Get the product that is beign clicked
    product = Product.objects.get(id=productId)
    #Create a new order if there isnt any, or get the current order
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    #Create a new orderItem if there isnt any, or get the current orderItem
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    #Handle adding 
    if action == 'add':
        print(quantity_value)
        #Check if the value is a valid number
        if quantity_value is not None:
            #Add the specified quantity
            orderItem.quantity = (orderItem.quantity + int(quantity_value))
        else:
            #Update by 1 (arrows interface)
            orderItem.quantity += 1
    #Handle removing
    elif action == 'remove':
        #Check if the value is a valid number
        if quantity_value is not None:
            #Subtract the specified quantity, ensuring it doesn't go below 0
            orderItem.quantity = max(0, orderItem.quantity - int(quantity_value))
        else:
            #Update by 1 (arrows interface)
            orderItem.quantity -= 1

    orderItem.save()

    #Delete the item of the order if the value reaches 0
    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)

def processOrder(request):
    # Generate a unique transaction ID using the current timestamp
    print("CREATING TRANSACTIO ID")
    transaction_id = datetime.datetime.now().timestamp()
    #Load data from the request body
    data = json.loads(request.body)

    #Check if the user is authenticated
    if request.user.is_authenticated:
        #If authenticated, associate the order with the authenticated customer
        customer = request.user.customer
        #Create order if there isn't any or get the current order
        order, created = Order.objects.get_or_create(customer = customer, complete=False)

    else:
        #If not authenticated, create a guest order using the guestOrder function
        customer, order = guestOrder(request, data)
    
    #Retrieve the total value from the form data
    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    #Check if the received total matches the cart total
    if float(total) == float(order.cartTotal):
        #If both totals match, change complete to True   
        order.complete = True

    order.save()

    #create a shipping address
    if order.shipping == True:
            ShippingAddress.objects.create(
                customer=customer,
                order=order,
                address=data['shipping']['address'],
                city=data['shipping']['city'],

ecommerce/store/templates/store/productview.html
{% extends 'store/templa.html' %}
{% load static %}
{% block content %}

    <div class="body3">
        <div class="show_product">
                <div>
                    <p>{{ product.name }}</p>
                </div>

            <img class="img_thumbnail" src="{{product.imageURL}}">
        </div>

        <div class="show_details">

            <div class="show_thumbnail">
                <p>{{ product.name }}</p>
            </div>
            
            <div class="prices">
            {% with product_discount=product.discountproduct_set.first %}
                {% if product_discount %}
                    <strong class="price_discount">{{ product_discount.discount_price|floatformat:2 }}€</strong>
                    <p class="old_price">{{ product.price|floatformat:2 }}€</p>
                {% else %}
                    <strong class="original_price">{{ product.price|floatformat:2 }}€</strong>
                {% endif %}
            {% endwith %}
            <br>
            <br>
            </div>

            <div class="col-xs-12 sizeselect">
                <div class="divSize" data-prompt="Selecione" data-outofstocktext="Está esgotado">
                    <p> Size :</p>
                </div>
                <div class="sizes">
                    <ul class="row sizebuttons" data-clicktoselecttext="Click to select">
                        <li>
                            <button type="button" class="btn btn-secondary size-button" data-size="36">
                                36
                            </button>
                        </li>
                        <li>
                            <button type="button" class="btn btn-secondary size-button" data-size="37">
                                37
                            </button>
                        </li>
                        <li>
                            <button type="button" class="btn btn-secondary size-button" data-size="38">
                                38
                            </button>
                        </li>
                        <li>
                            <button type="button" class="btn btn-secondary size-button" data-size="36">
                                39
                            </button>
                        </li>
                        <li>
                            <button type="button" class="btn btn-secondary size-button" data-size="37">
                                40
                            </button>
                        </li>
                        <li>
                            <button type="button" class="btn btn-secondary size-button" data-size="38">
                                41
                            </button>
                        </li>
                    </ul>
                </div>
                <div class="divQty">
                    <p> Quantity :</p>
                    <div class="qtypurchase">
                        <button class="quantity-control" data-product="{{ product.id }}" data-action="remove">-</button>
                            <div class="quantity-value" id="quantity-value"> {{ initial_quantity }} </div>
                        <button class="quantity-control" data-product="{{ product.id }}" data-action="add">+</button>
                    </div>
                </div>
            </div> 

            <div>
                <button data-product="{{ product.id }}" data-action="add" id="add-qty" class="btn btn-outline-secondary add-btn update-cart">
                <span>Add to Cart</span>
                <img src="{% static 'images/cart.png' %}" alt="Cart" id="cart-icon">
                </button>
            </div>
        </div>
        
        
    </div>

    <script>
        window.addEventListener('load', function () {
            var quantityValue = getCookiex('quantity') || {{ initial_quantity|default:1 }};
            
            document.getElementById('quantity-value').innerText = quantityValue;

            document.querySelector('.quantity-control[data-action="remove"]').addEventListener('click', function () {
                if (quantityValue > 1) {
                    quantityValue--;
                    document.getElementById('quantity-value').innerText = quantityValue;
                    setCookiex('quantity', quantityValue);
                }
            });

            document.querySelector('.quantity-control[data-action="add"]').addEventListener('click', function () {
                quantityValue++;
                document.getElementById('quantity-value').innerText = quantityValue;
                setCookiex('quantity', quantityValue);
            });

            // Function to set a cookie
            function setCookiex(name, value) {
                document.cookie = name + '=' + value + ';path=/';
            }

            // Function to get a cookie value
            function getCookiex(name) {
                var match = document.cookie.match(new RegExp('(^| )' + name + '=([^;]+)'));
                if (match) {
                    return match[2];
                }
                return null;
            }
        });
    </script>

{% endblock content %}

ecommerce/store/templates/store/search.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}

<nav class="navbar justify-content-center">
    <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/search/?search_str=M">Men</a></li>
        <li><a href="/search/?search_str=W">Woman</a></li>
        <li><a href="/search/?search_str=K">Kids</a></li>
    </ul>
</nav>

<div class="search-container">
    <form id="product-search-form" action="/search/" method="get">
        <input type="text" id="search-input" name="search_str" placeholder="Search for products..." value="{{ search_str }}">
        <button type="submit" class="btn btn-outline-secondary">Search</button>
    </form>
  </div>

<div class="sales-window">
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                {% if message.message == "No products found." %}
                    <div class="alert">
                        <h1>{{ message }}</h1>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <br>
        <br>
    {% endif %}
    
<div class="row">
    
        {% for product in products %}
        <div class="col-lg-4">
            <div class="box-element product">
                <img class="thumbnail" src="{{product.imageURL}}">
                <div class="product-description">
                    <div class="product-header">
                        <h6><strong> {{product.name}} </strong></h6>
                        <hr>
                    </div>
                    <div class="product-footer">
                        <div class="product-buttons">
                            {% csrf_token %}
                            <button data-product="{{ product.id }}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
                            <a class="btn btn-outline-success" href="{% url 'productview' product_name=product.name|urlize %}">View</a>
                        </div>
                        {% with product_discount=product.discountproduct_set.first %}
                            <h4>
                                {% if product_discount %}
                                    <strong style="color: red;">{{ product_discount.discount_price|floatformat:2 }}€</strong>
                                {% else %}
                                    <strong>{{ product.price|floatformat:2 }}€</strong>
                                {% endif %}
                            </h4>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    
</div>
</div>


{% endblock content %}

ecommerce/store/templates/store/store.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
    <!--<script>
        const csrftoken = getToken('csrftoken');
    </script>-->

    <nav class="navbar justify-content-center">
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/search/?search_str=M">Men</a></li>
            <li><a href="/search/?search_str=W">Woman</a></li>
            <li><a href="/search/?search_str=K">Kids</a></li>
        </ul>
    </nav>

    <div class="container">
    {% if discount %}
    <p class="offers">Special offers</p>

  <div class="discount-products-box">
    <button class="scroll-button left">←</button>
    <div class="products-container">
        {% for products in discount %}
        <a href="{% url 'productview' product_name=products.product.name|urlize %}" style="text-decoration: none;">
        <div class="disc-product">
            <img class="thumbnail" src="{{products.product.imageURL}}"> 
            <div class="discount-product">
                <h6><strong> {{products.product.name}} </strong></h6>
                <strong style="text-decoration: line-through; color: red;">{{ products.product.price }}</strong>
                <strong> {{products.discount_price}}€ </strong>
            </div>
        </div>
        </a>
        {% endfor %}
    </div>
    <button class="scroll-button right">→</button>
  </div>
  {% endif %}

  <section class="brand-logos">
    <a href="/search/?search_str=nike"><img src="{% static 'images/nike-logo.png' %}" alt="Brand 1"></a>
    <a href="/search/?search_str=adidas"><img src="{% static 'images/adidas-logo.png' %}" alt="Brand 2"></a>
    <a href="/search/?search_str=puma"><img src="{% static 'images/puma-logo.png' %}" alt="Brand 3"></a>
    <a href="/search/?search_str=asics"><img src="{% static 'images/asics-logo.png' %}" alt="Brand 3"></a>
    <!-- Add more brand logos with their respective links -->
  </section>

  

  <div class="search-container">
    <form id="product-search-form" action="/search/" method="get">
        <input type="text" id="search-input" name="search_str" placeholder="Search for products..." value="{{ search_str }}">
        <button type="submit" class="btn btn-outline-secondary">Search</button>
    </form>
  </div>

<div class="sales-window">
<div class="row">
    
        {% for product in products %}
        <div class="col-lg-4">
            <div class="box-element product">
                <img class="thumbnail" src="{{product.imageURL}}">
                <div class="product-description">
                    <div class="product-header">
                        <h6><strong> {{product.name}} </strong></h6>
                        <hr>
                    </div>
                    <div class="product-footer">
                        <div class="product-buttons">
                            {% csrf_token %}
                            <button data-product="{{ product.id }}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
                            <a class="btn btn-outline-success" href="{% url 'productview' product_name=product.name|urlize %}">View</a>
                        </div>
                        {% with product_discount=product.discountproduct_set.first %}
                            <h4>
                                {% if product_discount %}
                                    <strong style="color: red;">{{ product_discount.discount_price|floatformat:2 }}€</strong>
                                {% else %}
                                    <strong>{{ product.price|floatformat:2 }}€</strong>
                                {% endif %}
                            </h4>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    
</div>
</div>

</div>

<script>

document.addEventListener('DOMContentLoaded', () => {
    const productsContainer = document.querySelector('.products-container');
    const scrollLeftButton = document.querySelector('.scroll-button.left');
    const scrollRightButton = document.querySelector('.scroll-button.right');
    const scrollAmount = 10; // Adjust this value for the desired scroll speed

    scrollLeftButton.style.display = 'none'; // Initially hide the left-scroll button

    function animateScroll(scrollTo) {
        const currentScroll = productsContainer.scrollLeft;
        const difference = scrollTo - currentScroll;
        const step = Math.sign(difference) * scrollAmount;

        function scrollStep() {
            if ((step > 0 && productsContainer.scrollLeft >= scrollTo) || (step < 0 && productsContainer.scrollLeft <= scrollTo)) {
                productsContainer.scrollLeft = scrollTo;
            } else {
                productsContainer.scrollLeft += step;
                requestAnimationFrame(scrollStep);
            }
        }

        scrollStep();
    }

    function updateScrollButtons() {
        if (productsContainer.scrollLeft > 0) {
            scrollLeftButton.style.display = 'block';
        } else {
            scrollLeftButton.style.display = 'none';
        }

        const containerWidth = productsContainer.clientWidth;
        const maxScroll = productsContainer.scrollWidth - containerWidth;

        if (productsContainer.scrollLeft < maxScroll) {
            scrollRightButton.style.display = 'block';
        } else {
            scrollRightButton.style.display = 'none';
        }
    }

    productsContainer.addEventListener('scroll', () => {
        updateScrollButtons();
    });

    scrollLeftButton.addEventListener('click', () => {
        const scrollTo = Math.max(productsContainer.scrollLeft - 255, 0);
        animateScroll(scrollTo);
        updateScrollButtons();
    });

    scrollRightButton.addEventListener('click', () => {
        const containerWidth = productsContainer.clientWidth;
        const maxScroll = productsContainer.scrollWidth - containerWidth;
        const scrollTo = Math.min(productsContainer.scrollLeft + 260, maxScroll);
        animateScroll(scrollTo);
        updateScrollButtons();
    });

    // Initial button display
    updateScrollButtons();
});

</script>

{% endblock content %}

ecommerce/store/templates/store/transaction_sumary.html
{% extends 'store/templa.html' %}
{% load static %}
{% block content %}
<div class="body4">
    <div id="order-confirmation" class="box-element transactionsumary">
        <h3>Congratulations! Your transaction is complete.</h3>
        <hr>
        <h4>Order Summary:</h4>
        {% for item in order.orderitem_set.all %}
            <!-- Use order.orderitem_set.all to get all items associated with the order -->
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{{ item.product.imageURL }}"></div>
                <div style="flex:2; text-align: left;"><p>{{ item.product.name }}</p></div>
                <div style="flex:1"><p>{{ item.get_total|floatformat:2 }}€</p></div>
                <div style="flex:1"><p>{{ item.quantity }}</p></div>
            </div>
            <hr>
        {% endfor %}
        <hr>
        <h5>Items: {{ order.qnt_total }}</h5>
        <h5>Total: {{ order.cartTotal|floatformat:2 }}€</h5>
        <hr>
        <h4>Shipping Information:</h4>
        <p>Address: {{ shippingInfo.address }}</p>
        <p>City: {{ shippingInfo.city }}</p>
        <p>State: {{ shippingInfo.state }}</p>
        <p>Zip Code: {{ shippingInfo.zipcode }}</p>
    </div>
</div>

{% endblock content %}